Repository zb-developer2team/a-uction-FE, pull requests merged in 2023-04, with the labels that each got.

#6 Chore: [chore/#5/init] Init dev settings
  .eslintignore
  .eslintrc.cjs
  .gitignore
  .prettierignore
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  package-lock.json
  package.json
  public/style.css
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/tailwind.css
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: init

#11 Chore: [chore/#10/add_tailwind_setting] Configure additional tailwind dev settings
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  postcss.config.cjs
  tailwind.config.js
Labels: Config

#13 Feat: [feat/#12/image_component] Implement Image component
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.tsx
  src/components/Image/index.ts
Labels: feature

#15 Feat: [feat/#14/link_component] Implement Link component
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
  src/components/Link/index.ts
Labels: feature

#17 Feat: [feat/#16/input_component] Implement Input components
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/index.ts
Labels: feature

#19 Docs: Add PR template and Fix typo for issue template
  .github/ISSUE_TEMPLATE/-issue-template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: Docs

#22 Feat: [feat/#21/Icon_component] Implement Icon component
  src/assets/lock.png
  src/assets/search.png
  src/assets/user.png
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/index.ts
Labels: feature

#23 Feat: [feat/#9/Button_component] Implement Button Component
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/index.ts
Labels: feature

#25 Feat: [Feat/#20/dropdown component] Implement Dropdown component
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownItem.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/index.ts
Labels: feature

#28 Feat: [feat/#24/Image Button Component] Implement Image Button Component
  src/assets/SampleImage.png
  src/components/ImageButton/ImageButton.stories.tsx
  src/components/ImageButton/ImageButton.tsx
  src/components/ImageButton/index.ts
Labels: feature

#31 Feat: [feat/#30/Modal Component] Implement Modal Component
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/index.ts
Labels: feature

#34 Fix: [Fix/#33/fix components] Fix components
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.tsx
  src/components/ImageButton/ImageButton.tsx
Labels: Fix

#32 Feat: [Feat/#29/header] Implement Header component
  src/assets/auction.png
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/HeaderTop.tsx
  src/components/Header/index.ts
Labels: feature

#36 Fix: [Fix/#35/fix components] Fix Modal Components
  src/components/Modal/Modal.tsx
Labels: Fix

#39 Feat: [Feat/#38/Main Product] Implement Main Product
  src/components/Product/Product.stories.tsx
  src/components/Product/Product.tsx
  src/components/Product/index.ts
Labels: feature

#42 Feat: Implement Login page
  src/pages/Login/Login.stories.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/index.ts
Labels: feature

#43 Fix: [Fix/#41/fix components] Fix components
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.tsx
  src/components/Link/Link.tsx
Labels: Fix

#44 Feat: [Feat/#40/ProductDetail] Implement Product Detail
  src/components/ProductDetail/ProductDetail.stories.tsx
  src/components/ProductDetail/ProductDetail.tsx
  src/components/ProductDetail/index.ts
Labels: feature

#46 Feat: [Feat/#45/Profile] Implement Profile Component
  src/components/Profile/Profile.stories.tsx
  src/components/Profile/Profile.tsx
  src/components/Profile/index.ts
Labels: feature

#49 Feat: [Feat/#48/RadioButton] Implement Radio Button
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/index.ts
Labels: feature

#52 Fix: [Fix/#51/Radio Button] Fix components
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/RadioButton/RadioButton.tsx
Labels: Fix

#54 Feat: [feat/#50/signUp_page] Implement SignUp page
  src/pages/ SignUp/SignUp.stories.tsx
  src/pages/ SignUp/SignUp.tsx
  src/pages/ SignUp/index.ts
Labels: feature

#57 Fix: [Fix/#56/Product] Fix Product Component
  src/components/Product/Product.tsx
Labels: Fix

#59 Feat: [Feat/#53/input component] Implement additional Input component
  src/assets/mail.png
  src/assets/name.png
  src/assets/smartphone-call.png
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
Labels: Feature, Enhancement

#61 Fix: [Fix/#60/login and signup page] Fix Login and SignUp pages
  src/pages/Login/Login.tsx
  src/pages/SignUp/SignUp.stories.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/index.ts
Labels: Fix

#63 Fix: [fix/#62/Image_in_Input] Modify Image position in Input component
  src/components/Input/Input.tsx
Labels: Fix

#66 Fix: [Fix/#65/HeaderTop] Add 'imageType'properties
  src/components/Header/HeaderTop.tsx
Labels: Fix

#67 Feat: [Feat/#47/ProductRegist] Implement Product Regist Page
  src/pages/ProductRegist/ProductRegist.stories.tsx
  src/pages/ProductRegist/ProductRegist.tsx
  src/pages/ProductRegist/index.ts
Labels: Feature

#69 Feat: [Feat/#64/ProductDetailPage] Implement Product Detail Page
  src/pages/ProductDetailPage/ProductDetailPage.stories.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductDetailPage/index.ts
Labels: Feature

#74 Feat: [Feat/#73/DepositPage] Implement Deposit Page
  src/pages/DepositPage/DepositPage.stories.tsx
  src/pages/DepositPage/DepositPage.tsx
  src/pages/DepositPage/index.ts
Labels: Feature

#78 Feat: [Feat/#77/PaymentDone] Implement PaymentDone
  src/pages/PaymentDone/PaymentDone.stories.tsx
  src/pages/PaymentDone/PaymentDone.tsx
  src/pages/PaymentDone/index.ts
Labels: Feature

#76 Feat: [Feat/#75/SearchPage] Implement Search Page
  src/pages/SearchPage/SearchPage.stories.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/index.ts
Labels: Feature

#79 Feat: [feat/#70/bidding_page] Implement MyBidding page
  src/pages/MyBidding/MyBidding.stories.tsx
  src/pages/MyBidding/MyBidding.tsx
  src/pages/MyBidding/index.ts
Labels: Feature

#81 Fix: [Fix/#80/fix component] Fix Modal, Product Detail component
  src/components/Modal/Modal.tsx
  src/components/ProductDetail/ProductDetail.tsx
Labels: Fix

#83 Fix: [fix/#82/fix_productDetail] Fix css in ProductDetail page
  src/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: Fix

#85 Feat: [Feat/#84/PaymentPage] Implement PaymentPage
  src/pages/PaymentPage/PaymentPage.stories.tsx
  src/pages/PaymentPage/PaymentPage.tsx
  src/pages/PaymentPage/index.ts
Labels: Feature

#88 Feat: [Feat/#86/router] Implement router between pages
  index.html
  package-lock.json
  package.json
  src/components/Header/HeaderNav.tsx
  src/components/Header/HeaderTop.tsx
  src/components/Link/index.ts
  src/components/RadioButton/index.ts
  src/components/TextLink/TextLink.stories.tsx
  src/components/TextLink/TextLink.tsx
  src/components/TextLink/index.ts
  src/main.tsx
  src/pages/DepositPage/DepositPage.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/index.ts
  src/pages/PaymentDone/index.ts
  src/pages/ProductDetailPage/index.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SignUp/SignUp.tsx
Labels: Feature, Enhancement

#91 Feat: [feat/#90/productDetail] Connect product to Product detail page
  src/components/Product/Product.tsx
Labels: Enhancement

#93 Fix: [fix/#92/FixComponent] Fix the Input and Product Regist Page
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/pages/PaymentPage/index.ts
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Fix

#95 Remove: [remove/#94/remove_file] Remove unnecessary file
  src/App.css
  src/App.tsx
  src/index.css
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: Remove

#97 Feat: [feat/#96/Separate_component] Separate and Implement Component
  src/components/CategoryDetail/CategoryDetail.stories.tsx
  src/components/CategoryDetail/CategoryDetail.tsx
  src/components/CategoryDetail/index.ts
  src/components/ProductDetail/ProductDetail.stories.tsx
  src/components/ProductDetail/ProductDetail.tsx
  src/components/ProductPrice/ProductPrice.stories.tsx
  src/components/ProductPrice/ProductPrice.tsx
  src/components/ProductPrice/index.ts
  src/components/ProductTime/ProductTime.stories.tsx
  src/components/ProductTime/ProductTime.tsx
  src/components/ProductTime/index.ts
  src/components/Title/Title.stories.tsx
  src/components/Title/Title.tsx
  src/components/Title/index.ts
  src/pages/PaymentPage/PaymentPage.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: Feature, Fix

#101 Feat: [Feat/#100/FeatComponent] Separate Product Detail Component and Implement component
  src/components/ImageRegist/ImageRegist.stories.tsx
  src/components/ImageRegist/ImageRegist.tsx
  src/components/ImageRegist/index.ts
  src/components/MinBeedingPrice/MinBeedingPrice.stories.tsx
  src/components/MinBeedingPrice/MinBeedingPrice.tsx
  src/components/MinBeedingPrice/index.ts
  src/components/ProductCategory/ProductCategory.stories.tsx
  src/components/ProductCategory/ProductCategory.tsx
  src/components/ProductCategory/index.ts
  src/components/ProductInfo/ProductInfo.stories.tsx
  src/components/ProductInfo/ProductInfo.tsx
  src/components/ProductInfo/index.ts
  src/components/ProductName/ProductName.stories.tsx
  src/components/ProductName/ProductName.tsx
  src/components/ProductName/index.ts
  src/components/ProductStartPrice/ProductStartPrice.stories.tsx
  src/components/ProductStartPrice/ProductStartPrice.tsx
  src/components/ProductStartPrice/index.ts
  src/components/ProductStatus/ProductStatus.stories.tsx
  src/components/ProductStatus/ProductStatus.tsx
  src/components/ProductStatus/index.ts
  src/pages/ProductRegist/ProductRegist.stories.tsx
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Feature

#104 Refactor: [Refactor/#102/separate component] Refactor components in pages
  src/pages/Login/Login.tsx
  src/pages/Login/components/KakaoLogin/KakaoLogin.stories.tsx
  src/pages/Login/components/KakaoLogin/KakaoLogin.tsx
  src/pages/Login/components/KakaoLogin/index.ts
  src/pages/Login/components/LoginForm/LoginForm.stories.tsx
  src/pages/Login/components/LoginForm/LoginForm.tsx
  src/pages/Login/components/LoginForm/index.ts
  src/pages/Login/components/LoginTitle/LoginTitle.stories.tsx
  src/pages/Login/components/LoginTitle/LoginTitle.tsx
  src/pages/Login/components/LoginTitle/index.ts
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/SignUpForm/SignUpForm.stories.tsx
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
  src/pages/SignUp/components/SignUpForm/index.ts
  src/pages/SignUp/components/SignUpTitle/SignUpTitle.stories.tsx
  src/pages/SignUp/components/SignUpTitle/SignUpTitle.tsx
  src/pages/SignUp/components/SignUpTitle/index.ts
Labels: Refactor, Enhancement

#107 Style: [style/#105/fix_name] Change Title name in storybook file
  src/components/ProductCategory/ProductCategory.stories.tsx
Labels: Style

#113 Config: [config/#112] Add API & Query folder
  src/api/ProductInfo/getProductInfo.ts
  src/queries/useProductInfoQuery.tsx
Labels: Config

#111 Enhancement: [Enhancement/#110] Enhancement component for product regist
  src/components/MinBeedingPrice/MinBeedingPrice.tsx
  src/components/ProductName/ProductName.tsx
  src/components/ProductStartPrice/ProductStartPrice.tsx
Labels: Enhancement

#115 Feat: [Feat/#103/validation] Implement Login, SignUp validation
  src/pages/Login/components/LoginForm/LoginForm.tsx
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
Labels: Feature

#119 Feat: [feat/#118/DateTimeComponent] Implement Start/End DateTime component
  src/components/EndDateTime/EndDateTime.stories.tsx
  src/components/EndDateTime/EndDateTime.tsx
  src/components/EndDateTime/index.ts
  src/components/StartDateTime/StartDateTime.stories.tsx
  src/components/StartDateTime/StartDateTime.tsx
  src/components/StartDateTime/index.ts
Labels: Feature

#117 Feat: [feat/#116/DateTimePicker] Add DateTimePicker Library
  src/components/DateTimePicker/DateTimePicker.tsx
Labels: Feature

#120 Fix: [fix/#114/add_type] Add password type in Input component
  src/components/Input/Input.tsx
  src/pages/Login/components/LoginForm/LoginForm.tsx
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
Labels: Fix

#129 Enhancement: [#128/RadioButton] Enhancement Radio Button
  src/components/ProductStatus/ProductStatus.tsx
  src/components/RadioButton/RadioButton.tsx
Labels: Fix, Enhancement

#127 Docs: [Docs/#126] Add Token value
  src/main.tsx
Labels: Docs

#125 Enhancement: [Enhancement/#124] Add description API & Enhancement product info component
  src/api/ProductInfo/getProductInfo.ts
  src/components/ProductInfo/ProductInfo.tsx
Labels: Enhancement

#123 Enhancement: [Enhancement/#122/Dropdown] Enhancement Dropdown/ Product Category component
  src/components/Dropdown/DropdownMenu.tsx
  src/components/ProductCategory/ProductCategory.tsx
Labels: Enhancement

#131 Enhancement: [Enhancement/#130/DateTimePicker] Enhance Date Time Picker
  src/components/DateTimePicker/DateTimePicker.tsx
  src/components/EndDateTime/EndDateTime.tsx
  src/components/StartDateTime/StartDateTime.tsx
Labels: Enhancement

#133 Fix: [Fix/#132/Router] Fix the Router structure
  src/main.tsx
Labels: Fix

#135 Feat: [feat/#134/ProductRegist] Implement Product Regist
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Feature

#137 Config :[Config/#136] Config and Add Library
  package-lock.json
  package.json
  src/api/ProductInfo/getProductInfo.ts
Labels: Config

#141 Fix: [fix/#140/button_type] Add button type in Button component
  src/components/Button/Button.tsx
Labels: Fix

#143 Fix: [Fix/#142] Fix the Tab List
  src/pages/MyPage/MyPage.tsx
Labels: Fix

#145 Enhancement: [Enhancement/#144] Implement image upload with multi-part-file
  src/api/ProductInfo/getProductInfo.ts
  src/components/ImageRegist/ImageRegist.tsx
  src/pages/ProductRegist/ProductRegist.tsx
  src/queries/useProductInfoQuery.tsx
Labels: Enhancement

#148 Fix: [fix/#147/type_error] Fix type error
  src/pages/MyBidding/MyBidding.tsx
Labels: Fix

#150 Fix: [fix/#149/import_code] Fix import code
  src/queries/useProductInfoQuery.tsx
Labels: Fix

#152 Fix: [Fix/#151] Fix API from files to imageSrc
  src/api/ProductInfo/getProductInfo.ts
  src/queries/useProductInfoQuery.tsx
Labels: Fix

#156 Enhancement: [Enhancement/#153] MinBiddingPrice & StartPrice validation
  src/components/MinBeedingPrice/MinBeedingPrice.tsx
  src/components/ProductStartPrice/ProductStartPrice.tsx
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Enhancement

#158 Fix: [fix/#157/absolute_path] Change image path to absolute path
  .gitignore
  package-lock.json
  package.json
  public/assets/Banner.png
  public/assets/SampleImage.png
  public/assets/auction.png
  public/assets/lock.png
  public/assets/mail.png
  public/assets/name.png
  public/assets/search.png
  public/assets/smartphone-call.png
  public/assets/user.png
  src/assets/react.svg
  src/components/Header/HeaderTop.tsx
  src/components/Input/Input.tsx
  src/components/Product/Product.tsx
  src/components/ProductDetail/ProductDetail.tsx
  src/pages/Login/components/LoginTitle/LoginTitle.tsx
  src/pages/MyPage/MyPage.tsx
  tsconfig.json
  vite.config.ts
Labels: Fix

#160 Fix: [fix/#159/react_module] Add React module
  src/components/Button/Button.tsx
  src/components/CategoryDetail/CategoryDetail.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownItem.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/EndDateTime/EndDateTime.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/HeaderTop.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/ImageButton/ImageButton.tsx
  src/components/ImageRegist/ImageRegist.tsx
  src/components/Input/Input.tsx
  src/components/MinBeedingPrice/MinBeedingPrice.tsx
  src/components/Modal/Modal.tsx
  src/components/Product/Product.tsx
  src/components/ProductCategory/ProductCategory.tsx
  src/components/ProductDetail/ProductDetail.tsx
  src/components/ProductInfo/ProductInfo.tsx
  src/components/ProductName/ProductName.tsx
  src/components/ProductPrice/ProductPrice.tsx
  src/components/ProductStartPrice/ProductStartPrice.tsx
  src/components/ProductStatus/ProductStatus.tsx
  src/components/ProductTime/ProductTime.tsx
  src/components/Profile/Profile.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/StartDateTime/StartDateTime.tsx
  src/components/TextLink/TextLink.tsx
  src/components/Title/Title.tsx
  src/pages/DepositPage/DepositPage.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/KakaoLogin/KakaoLogin.tsx
  src/pages/Login/components/LoginForm/LoginForm.tsx
  src/pages/Login/components/LoginTitle/LoginTitle.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MyBidding/MyBidding.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/PaymentDone/PaymentDone.tsx
  src/pages/PaymentPage/PaymentPage.tsx
  src/pages/Preparing/Preparing.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductRegist/ProductRegist.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/SignUpTitle/SignUpTitle.tsx
Labels: Fix

#162 Fix: [fix/#161/type_error] Fix errors when adding images in tsx file
  src/types/images.d.ts
  tsconfig.json
Labels: Fix

#164 Fix: [fix/#163/env_error] Fix 'env' not present on type 'ImportMeta'
  tsconfig.json
Labels: Fix

#166 Fix: [fix/#165/image] Modify image path to absolute path
  src/pages/SignUp/components/SignUpTitle/SignUpTitle.tsx
Labels: Fix

#168 Fix: [fix/#167/login_page] Delete Link tag in LoginForm component
  src/pages/Login/components/LoginForm/LoginForm.tsx
Labels: Fix

#170 Fix: [Fix/#169/cors error] Add proxy code to vite config file
  src/setProxy.js
  vite.config.ts
Labels: Bug, Config, Fix

#171 Feat: [feat/#121/signup] Implement member signup
  src/api/SignUpInfo/user.ts
  src/hook/useSignUp.ts
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
Labels: Feature

#174 Enhancemet: [Enhancement/#173] StartDateTime & EndDateTime validation
  src/components/EndDateTime/EndDateTime.tsx
  src/components/StartDateTime/StartDateTime.tsx
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Enhancement

#176 Fix: [Fix/#175] Fix the API name from 'imagesSrc' to 'files'
  src/api/ProductInfo/getProductInfo.ts
  src/pages/ProductRegist/ProductRegist.tsx
  src/queries/useProductInfoQuery.tsx
Labels: Fix

#178 Fix: [Fix/#177] Fix page style
  src/components/ProductDetail/ProductDetail.tsx
Labels: Fix

#179 Feat: [Feat/#172/login] Implement Login
  package-lock.json
  package.json
  src/api/LoginInfo/user.ts
  src/components/Header/Header.tsx
  src/hook/useLogin.ts
  src/main.tsx
  src/pages/Login/components/LoginForm/LoginForm.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/recoil/atom.ts
Labels: Feature, Enhancement

#181 Bug: [bug/#180/mixed_content_error] Add code to resolve mixed content error
  index.html
Labels: Bug

#183 Enhancement: [Enhancement/#182] Enhancement Product / Search Page
  src/components/Product/Product.tsx
  src/main.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SearchPage/SearchPage.stories.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: Enhancement

#185 Fix: [Fix/#184] Fix the Radio Button status
  src/components/ProductStatus/ProductStatus.tsx
  src/components/RadioButton/RadioButton.tsx
Labels: Fix

#187 Fix: [fix/#186/banner] Fix banner size
  src/pages/MainPage/MainPage.tsx
Labels: Fix

#189 Fix: [fix/#188/server] Change Server address
  src/hook/useLogin.ts
  src/hook/useSignUp.ts
  src/setProxy.js
  vite.config.ts
Labels: Fix

#193 Fix: [Fix/#192] Fix the dropdown category menu
  src/components/Dropdown/DropdownMenu.tsx
Labels: Fix

#191 Fix: [Fix/#190] Fix the Header title
  src/components/Header/HeaderNav.tsx
Labels: Fix

#197 Fix: [Fix/#196] Fix the BE server address
  src/api/ProductInfo/getProductInfo.ts
  src/pages/ProductRegist/ProductRegist.tsx
  src/queries/useProductInfoQuery.tsx
Labels: Fix

#195 Enhancement: [Enhancement/#194] Add dummydata on Main Page
  src/pages/MainPage/MainPage.tsx
Labels: Enhancement

#199 Enhancement:[Enhancement/#198] Add price button component / Implement button status
  src/components/Button/Button.stories.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: Enhancement
