Repository zb-developer2team/a-uction-FE, pull requests merged in 2023-05, with the labels that each got.

#203 Feat: [Feat/#200] Implement product modify page
  package-lock.json
  package.json
  src/api/ProductInfo/getFixInfo.ts
  src/pages/ProductFix/ProductFix.stories.tsx
  src/pages/ProductFix/ProductFix.tsx
  src/pages/ProductFix/index.ts
  src/queries/useFixInfoQuery.tsx
Labels: Feature

#204 Fix: [fix/#201] Add productfix router
  src/main.tsx
Labels: Fix

#206 Fix: [Fix/#205] Fix the category properties
  src/components/Dropdown/DropdownMenu.tsx
Labels: Fix

#208 Enhancement: [Enhancement/#207] Enhancement rendering of product list
  src/pages/MyPage/MyPage.tsx
  src/pages/Participated/Participated.stories.tsx
  src/pages/Participated/Participated.tsx
  src/pages/Participated/index.ts
  src/pages/Purchased/Purchased.stories.tsx
  src/pages/Purchased/Purchased.tsx
  src/pages/Purchased/index.ts
  src/pages/Registered/Registered.stories.tsx
  src/pages/Registered/Registered.tsx
  src/pages/Registered/index.ts
Labels: Enhancement

#210 Fix: [Fix/#209] Fix the code of product regist
  src/api/ProductInfo/getProductInfo.ts
  src/components/ImageRegist/ImageRegist.tsx
  src/pages/ProductRegist/ProductRegist.tsx
Labels: Fix

#214 Fix: [ Fix/#213/button ] Change Duplication button state
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
Labels: Fix

#216 Enhancement: [Enhancement/#215] Fix product component for image rendering
  src/components/Image/Image.tsx
  src/components/Product/Product.stories.tsx
  src/components/Product/Product.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/Participated/Participated.tsx
  src/pages/Preparing/Preparing.tsx
  src/pages/Purchased/Purchased.tsx
  src/pages/Registered/Registered.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: Enhancement

#218 Feat: [ Feat/#217/validate number ] Implement Validate number
  src/components/Input/Input.tsx
  src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
Labels: Feature, Enhancement

#220 Enhancement: [enhancement/#219] Fix page and add error code status
  src/pages/SearchPage/SearchPage.tsx
Labels: Enhancement

#222 Enhancement: [Enhancement/#221] Enhancement register page for data rendering
  src/pages/Registered/Registered.tsx
Labels: Enhancement

#224 Enhancement: [Enhancement/#223] Fix upcoming page
  src/pages/Upcoming/Upcoming.stories.tsx
  src/pages/Upcoming/Upcoming.tsx
  src/pages/Upcoming/index.ts
Labels: Enhancement

#226 Enhancement: [enhancement/#225] Fix the result bidding page
  src/pages/Result/Result.stories.tsx
  src/pages/Result/Result.tsx
  src/pages/Result/index.ts
Labels: Enhancement

#228 Fix: [Fix/#227] Fix the router
  src/main.tsx
Labels: Fix

#230 Enhancement: [Enhancement/#229] Link to deposit page
  src/components/Profile/Profile.tsx
Labels: Enhancement

#232 Fix: [fix/#231/main_layout] Adjust the main page product layout
  src/pages/MainPage/MainPage.tsx
Labels: Fix

#234 Enhancement: [enhancement/#233] Enhancement the page
  src/pages/Participated/Participated.tsx
  src/pages/ParticipatedBidding/ParticipatedBidding.stories.tsx
  src/pages/ParticipatedBidding/ParticipatedBidding.tsx
  src/pages/ParticipatedBidding/index.ts
Labels: Enhancement

#236 Fix: [fix/#235/preparing] Modify components to make them reusable
  src/pages/Preparing/Preparing.tsx
Labels: Fix, Enhancement

#238 Fix: [fix/#237/error_page] Add error page
  src/pages/Result/Result.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/Upcoming/Upcoming.tsx
Labels: Fix

#240 Enhancement: [Enhancement/#239] Enhancement purchased page
  src/pages/ErrorCodePage/ErrorCodePage.stories.tsx
  src/pages/ErrorCodePage/ErrorCodePage.tsx
  src/pages/ErrorCodePage/index.ts
  src/pages/Participated/Participated.tsx
  src/pages/ParticipatedBidding/ParticipatedBidding.stories.tsx
  src/pages/ParticipatedBidding/index.ts
  src/pages/Purchased/Purchased.tsx
Labels: Enhancement

#242 Feat: [Feat/#241/info page] Implement Information page
  src/components/Header/HeaderNav.tsx
  src/main.tsx
  src/pages/Information/Information.stories.tsx
  src/pages/Information/Information.tsx
  src/pages/Information/index.ts
Labels: Feature, Enhancement

#246 Feat: [feat/#245/header_nav] Change header navigation style
  src/components/Header/HeaderNav.tsx
Labels: Enhancement

#250 Fix: [Fix/#249/change list] Change render auction list
  src/main.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/Result/Result.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/Upcoming/Upcoming.tsx
Labels: Fix

#252 Feat: [feat/#251] Implement product modify
  src/main.tsx
  src/pages/ProductDetailModify/ProductDetailModify.stories.tsx
  src/pages/ProductDetailModify/ProductDetailModify.tsx
  src/pages/ProductDetailModify/index.ts
  src/pages/ProductFix/ProductFix.tsx
Labels: Feature

#254 Feat: [feat/#253/kakao_login] Connect Kakao login URL
  src/pages/Login/components/KakaoLogin/KakaoLogin.tsx
Labels: Feature

#256 Enhancement: [enhancement/#255] Enhancement product modify page
  src/components/RegisteredProduct/RegisteredProduct.tsx
  src/components/RegisteredProduct/RegisteredProdut.stories.tsx
  src/components/RegisteredProduct/index.ts
  src/pages/Registered/Registered.tsx
Labels: Enhancement

#258 Fix: [Fix/#257] Fix the main page
  src/pages/MainPage/MainPage.tsx
Labels: Fix

#260 Feat: [Feat/#259/detail page] Connect Detail page
  src/components/Product/Product.tsx
  src/components/ProductDetail/ProductDetail.tsx
  src/components/Title/Title.tsx
  src/main.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/Participated/Participated.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/Purchased/Purchased.tsx
  src/pages/Result/Result.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/Upcoming/Upcoming.tsx
  tsconfig.json
Labels: Feature, Enhancement
